# Generated by Django 5.2.8 on 2025-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_delete_camment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/%d/'),
        ),
    ]
